version: '3'
services:
  backend:
    image: 'maven:3-jdk-8-alpine'
    volumes:
     - ./back-end:/app/
    command: mvn clean spring-boot:run
    working_dir: /app
    ports:
     - 8080:8080

  frontend:
    image: 'node:lts-alpine'
    volumes:
     - ./front-web:/app/
    command: sh -c "yarn install && yarn start"
    working_dir: /app
    ports:
     - 3000:3000